/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package br.com.ifba.curso.view;

import br.com.ifba.curso.dao.CursoDao;
import br.com.ifba.curso.dao.CursoIDao;
import br.com.ifba.curso.entity.Curso;
import java.awt.event.WindowEvent;
import javax.swing.JOptionPane;

/**
 *
 * @author rober
 */
public class CursoEditar extends javax.swing.JFrame {
    
    /**
     * Instância da classe {@code CursoListar}, responsável pela listagem de cursos.
     * 
     * Esta instância é utilizada para atualizar a lista de cursos exibida após o cadastro ou edição de um curso.
     */
    private CursoListar curso;
    
    /*
     * Id do item que deve ser editado
     */
    private long idItemEditar;
    
    /** 
    * Objeto de acesso a dados (DAO) para a entidade {@link Curso}.
    * 
    * Inicializado com uma implementação de {@link CursoDao}, permite realizar
    * operações de persistência específicas para a entidade {@link Curso}.
    */
    CursoIDao cursoDao = new CursoDao();
    
    /**
     * Creates new form CursoCadastro
     */
    public CursoEditar() {
        initComponents();
    }
    
    /**
    * Construtor da classe CursoEditar.
    * 
    * Este construtor é utilizado para inicializar a interface gráfica de edição de um curso. Ele recebe
    * como parâmetros uma instância da classe {@link CursoListar}, que será utilizada para atualizar a tabela
    * após a edição, e o ID do curso a ser editado, {@code idItemEditar}, que identifica o curso no banco de dados.
    * 
    * @param curso A instância da classe {@link CursoListar} que permite atualizar a tabela de cursos.
    * @param idItemEditar O ID do curso que será editado.
    */
    public CursoEditar(CursoListar curso, long idItemEditar) {
        initComponents();
        this.curso = curso;
        this.idItemEditar = idItemEditar;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnGroupStatus = new javax.swing.ButtonGroup();
        btnSalvarAlteracoes = new javax.swing.JButton();
        btnCancelar = new javax.swing.JButton();
        radioBtnInativo = new javax.swing.JRadioButton();
        radioBtnAtivo = new javax.swing.JRadioButton();
        lblTextoStatus = new javax.swing.JLabel();
        lblTextoCodigo = new javax.swing.JLabel();
        lblTextoNome = new javax.swing.JLabel();
        txtNome = new javax.swing.JTextField();
        txtCodigo = new javax.swing.JTextField();
        lblTextoEditarCurso = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setResizable(false);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosed(java.awt.event.WindowEvent evt) {
                formWindowClosed(evt);
            }
        });

        btnSalvarAlteracoes.setFont(new java.awt.Font("Times New Roman", 0, 16)); // NOI18N
        btnSalvarAlteracoes.setText("Salvar");
        btnSalvarAlteracoes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalvarAlteracoesActionPerformed(evt);
            }
        });

        btnCancelar.setFont(new java.awt.Font("Times New Roman", 0, 16)); // NOI18N
        btnCancelar.setText("Cancelar");
        btnCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelarActionPerformed(evt);
            }
        });

        btnGroupStatus.add(radioBtnInativo);
        radioBtnInativo.setText("Inativo");
        radioBtnInativo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                radioBtnInativoActionPerformed(evt);
            }
        });

        btnGroupStatus.add(radioBtnAtivo);
        radioBtnAtivo.setText("Ativo");

        lblTextoStatus.setFont(new java.awt.Font("Times New Roman", 0, 16)); // NOI18N
        lblTextoStatus.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblTextoStatus.setText("Status");

        lblTextoCodigo.setFont(new java.awt.Font("Times New Roman", 0, 16)); // NOI18N
        lblTextoCodigo.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblTextoCodigo.setText("Código Curso");

        lblTextoNome.setFont(new java.awt.Font("Times New Roman", 0, 16)); // NOI18N
        lblTextoNome.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblTextoNome.setText("Nome");

        txtNome.setFont(new java.awt.Font("Times New Roman", 0, 16)); // NOI18N

        txtCodigo.setFont(new java.awt.Font("Times New Roman", 0, 16)); // NOI18N

        lblTextoEditarCurso.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        lblTextoEditarCurso.setText("Editar Curso");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(lblTextoEditarCurso)
                .addGap(115, 115, 115))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(94, 94, 94)
                        .addComponent(btnCancelar)
                        .addGap(59, 59, 59)
                        .addComponent(btnSalvarAlteracoes))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lblTextoStatus, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(radioBtnAtivo, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(radioBtnInativo, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(lblTextoCodigo, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblTextoNome))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtNome, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtCodigo, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(45, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(lblTextoEditarCurso)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 38, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(lblTextoNome)
                    .addComponent(txtNome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtCodigo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblTextoCodigo))
                .addGap(21, 21, 21)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblTextoStatus)
                    .addComponent(radioBtnAtivo)
                    .addComponent(radioBtnInativo))
                .addGap(41, 41, 41)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnCancelar)
                    .addComponent(btnSalvarAlteracoes))
                .addGap(37, 37, 37))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    /**
    * Método acionado quando o botão "Salvar Alterações" é clicado.
    * 
    * Verifica se os campos obrigatórios (nome, código e status do curso) estão preenchidos. 
    * Caso algum campo esteja vazio, exibe uma mensagem de alerta ao usuário. 
    * Se todos os campos estiverem preenchidos, cria um objeto {@link Curso}, preenche seus 
    * atributos com os dados informados (incluindo o ID do curso a ser editado) e atualiza 
    * as informações do curso no banco de dados usando {@code cursoDao}.
    * 
    * Após salvar as alterações, exibe uma mensagem de sucesso ao usuário.
    * 
    * @param evt o evento acionado pelo clique no botão "Salvar Alterações".
    */
    private void btnSalvarAlteracoesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalvarAlteracoesActionPerformed
        if (txtNome.getText().equals("") || 
                txtCodigo.getText().equals("") || 
                (!radioBtnAtivo.isSelected() && !radioBtnInativo.isSelected())) 
        {
            JOptionPane.showMessageDialog(
            null, "Existem campos vazios, preencha todos e tente novamente!",
            "Alerta", JOptionPane.WARNING_MESSAGE);
        } else {
            Curso curso = new Curso();
            curso.setId(idItemEditar);
            curso.setNome(txtNome.getText());
            curso.setCodigoCurso(txtCodigo.getText());
            if (radioBtnAtivo.isSelected()) {
                curso.setAtivo(true);
            } else {
                curso.setAtivo(false);
            }
            cursoDao.update(curso);
            JOptionPane.showMessageDialog(
            null, "Curso Editado com Sucesso!",
            "Salvo", JOptionPane.INFORMATION_MESSAGE);
        }
    }//GEN-LAST:event_btnSalvarAlteracoesActionPerformed

     /**
    * Método responsável por tratar o evento de clique no botão "Cancelar" da interface gráfica.
    * 
    * Este método limpa todos os campos de entrada do formulário
    * 
    * @param evt O evento de ação gerado pelo clique no botão "Cancelar".
    */
    private void btnCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelarActionPerformed
        txtNome.setText(""); 
        txtCodigo.setText("");
        radioBtnAtivo.setSelected(false);
        btnGroupStatus.clearSelection();
    }//GEN-LAST:event_btnCancelarActionPerformed

    private void radioBtnInativoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_radioBtnInativoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_radioBtnInativoActionPerformed

    /**
    * Método responsável por tratar o evento de fechamento da janela.
    * 
    * Este método é chamado quando a janela da aplicação é fechada. Ele verifica se a instância da classe 
    * {@link CursoListar} está disponível e, caso esteja, chama o método {@link CursoListar#updateTable} para 
    * atualizar a tabela de cursos exibida na interface gráfica.
    * 
    * @param evt O evento de janela que ocorre quando a janela é fechada.
    */
    private void formWindowClosed(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosed
        if (this.curso != null) {
            this.curso.updateTable();
        }
    }//GEN-LAST:event_formWindowClosed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CursoEditar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CursoEditar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CursoEditar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CursoEditar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CursoEditar().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCancelar;
    private javax.swing.ButtonGroup btnGroupStatus;
    private javax.swing.JButton btnSalvarAlteracoes;
    private javax.swing.JLabel lblTextoCodigo;
    private javax.swing.JLabel lblTextoEditarCurso;
    private javax.swing.JLabel lblTextoNome;
    private javax.swing.JLabel lblTextoStatus;
    private javax.swing.JRadioButton radioBtnAtivo;
    private javax.swing.JRadioButton radioBtnInativo;
    private javax.swing.JTextField txtCodigo;
    private javax.swing.JTextField txtNome;
    // End of variables declaration//GEN-END:variables
}
